name: Build Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ubuntu-build-check:
    name: Ubuntu Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        run: sudo apt install -y libcurl4-openssl-dev libtag1-dev libfaad-dev libogg-dev libfftw3-dev libopus-dev libopusfile-dev libvorbis-dev libchafa-dev libavformat-dev libstb-dev libglib2.0-dev

      - name: Build code
        run: make
